### ISSUE TITLE
Not accepting custom field names

### ISSUE THREAD

**Issue by andreagreening** [GeneaLabs/nova-map-marker-field#10]
I am trying to use custom field names by following the documentation:
`MapMarker::make('Location')
            ->latitude('lat')
            ->longitude('long'),`

But these fields stay blank.  If I rename these fields to 'latitude' & 'longitude' in my database, everything works great.  I do not want to rename my fields though, can you provide any assistance?

**Comment by mikebronner** [comment]
@andreagreening Absolutely, thanks for reporting this. Let me work on that in the morning and see if I can replicate the issue. If I can, I will work on a fix and have it to you as soon as possible tomorrow.

**Comment by andreagreening** [comment]
@mikebronner Thanks so much for your speedy response!

**Comment by mikebronner** [comment]
Hi @andreagreening, thanks for being patient with this issue. This should now be fixed in release 0.1.3.
Saving was working correctly, it was the detail page that wasn't reading non-default field names correctly. Please let me know how this works for you. 😀

**Comment by andreagreening** [comment]
This works on the detail page. Thank you! However, it still appears to not be loading the Location Data on the Resource Index.

**Comment by mikebronner** [comment]
@andreagreening Oh bugger!!!! hang tight, I'll have a fix up in a sec.

**Comment by mikebronner** [comment]
Can you give release 0.1.4 a shot? Hopefully this works now. :)

**Comment by andreagreening** [comment]
That works!

**Comment by mikebronner** [comment]
@andreagreening Awesome, glad things are up and running!

**Comment by andreagreening** [comment]
Thanks for all your help!

**Comment by mikebronner** [comment]
Anytime, please let me know if you run into trouble or have suggestions down the road. :)
